# Generated by Django 4.1 on 2022-08-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosterName', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RosterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RosterChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.character')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosterchoices', to='nocapapi.roster')),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.rosteruser'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='primary_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primaryweapon', to='nocapapi.weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.role'),
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondaryweapon', to='nocapapi.weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.server'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.rosteruser'),
        ),
        migrations.CreateModel(
            name='CalculatedRosterChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.BigIntegerField()),
                ('healing', models.BigIntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('calculated_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculatedrosterchoices', to='nocapapi.calculatedroster')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.character')),
            ],
        ),
        migrations.AddField(
            model_name='calculatedroster',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated', to='nocapapi.roster'),
        ),
        migrations.AddField(
            model_name='calculatedroster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.rosteruser'),
        ),
    ]
