# Generated by Django 4.1 on 2022-08-09 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedroster',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated', to='nocapapi.roster'),
        ),
    ]
