# Generated by Django 4.1 on 2022-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0002_alter_calculatedroster_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='name',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedroster',
            name='rosterName',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
