# Generated by Django 4.1 on 2022-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0003_roster_name_alter_calculatedroster_rostername'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.CharField(max_length=500, null=True, verbose_name='notes'),
        ),
    ]
