# Generated by Django 4.1 on 2022-09-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0005_charlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharLinks',
            new_name='CharLink',
        ),
    ]
