# Generated by Django 4.1.3 on 2022-11-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0005_charlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedrosterchoices',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
