# Generated by Django 4.1 on 2022-09-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0006_rename_charlinks_charlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlink',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_roster', to='nocapapi.calculatedroster'),
        ),
    ]
