# Generated by Django 4.1.4 on 2022-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0006_calculatedrosterchoices_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to='characterimages'),
        ),
    ]
