# Generated by Django 4.1.6 on 2023-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0007_character_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rosterchoices',
            constraint=models.UniqueConstraint(fields=('roster', 'character'), name='unique_roster_character_choices'),
        ),
    ]
