# Generated by Django 4.1.6 on 2023-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0008_rosterchoices_unique_roster_character_choices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calculatedrosterchoices',
            constraint=models.UniqueConstraint(fields=('character', 'calculated_roster'), name='unique_character_calculated_roster'),
        ),
    ]
