# Generated by Django 4.1.6 on 2023-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0009_calculatedrosterchoices_unique_character_calculated_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterchoices',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
