# Generated by Django 4.1.6 on 2023-03-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0010_rosterchoices_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlink',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='nocapapi.character'),
        ),
    ]
