# Generated by Django 4.1.6 on 2023-04-06 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0014_calculatedroster_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCalculatedRosterChoiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.calculatedroster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nocapapi.rosteruser')),
            ],
        ),
    ]
