# Generated by Django 4.1.6 on 2023-04-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0015_sharedcalculatedrosterchoicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedroster',
            name='created_at',
        ),
        migrations.AddField(
            model_name='calculatedroster',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nocapapi.server'),
        ),
    ]
