# Generated by Django 4.1.6 on 2023-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocapapi', '0016_remove_calculatedroster_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedroster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
